// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: arquivo.proto

package com.example;

public final class Arquivo {
  private Arquivo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UniversidadeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.example.Universidade)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string nome = 1;</code>
     * @return The nome.
     */
    java.lang.String getNome();
    /**
     * <code>string nome = 1;</code>
     * @return The bytes for nome.
     */
    com.google.protobuf.ByteString
        getNomeBytes();

    /**
     * <code>int32 anoInstituicao = 2;</code>
     * @return The anoInstituicao.
     */
    int getAnoInstituicao();

    /**
     * <code>repeated .com.example.Professor professores = 3;</code>
     */
    java.util.List<com.example.Arquivo.Professor> 
        getProfessoresList();
    /**
     * <code>repeated .com.example.Professor professores = 3;</code>
     */
    com.example.Arquivo.Professor getProfessores(int index);
    /**
     * <code>repeated .com.example.Professor professores = 3;</code>
     */
    int getProfessoresCount();
    /**
     * <code>repeated .com.example.Professor professores = 3;</code>
     */
    java.util.List<? extends com.example.Arquivo.ProfessorOrBuilder> 
        getProfessoresOrBuilderList();
    /**
     * <code>repeated .com.example.Professor professores = 3;</code>
     */
    com.example.Arquivo.ProfessorOrBuilder getProfessoresOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.example.Universidade}
   */
  public static final class Universidade extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.example.Universidade)
      UniversidadeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Universidade.newBuilder() to construct.
    private Universidade(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Universidade() {
      nome_ = "";
      professores_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Universidade();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Universidade(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              nome_ = s;
              break;
            }
            case 16: {

              anoInstituicao_ = input.readInt32();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                professores_ = new java.util.ArrayList<com.example.Arquivo.Professor>();
                mutable_bitField0_ |= 0x00000001;
              }
              professores_.add(
                  input.readMessage(com.example.Arquivo.Professor.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          professores_ = java.util.Collections.unmodifiableList(professores_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.Arquivo.internal_static_com_example_Universidade_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.Arquivo.internal_static_com_example_Universidade_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.Arquivo.Universidade.class, com.example.Arquivo.Universidade.Builder.class);
    }

    public static final int NOME_FIELD_NUMBER = 1;
    private volatile java.lang.Object nome_;
    /**
     * <code>string nome = 1;</code>
     * @return The nome.
     */
    @java.lang.Override
    public java.lang.String getNome() {
      java.lang.Object ref = nome_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nome_ = s;
        return s;
      }
    }
    /**
     * <code>string nome = 1;</code>
     * @return The bytes for nome.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNomeBytes() {
      java.lang.Object ref = nome_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nome_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ANOINSTITUICAO_FIELD_NUMBER = 2;
    private int anoInstituicao_;
    /**
     * <code>int32 anoInstituicao = 2;</code>
     * @return The anoInstituicao.
     */
    @java.lang.Override
    public int getAnoInstituicao() {
      return anoInstituicao_;
    }

    public static final int PROFESSORES_FIELD_NUMBER = 3;
    private java.util.List<com.example.Arquivo.Professor> professores_;
    /**
     * <code>repeated .com.example.Professor professores = 3;</code>
     */
    @java.lang.Override
    public java.util.List<com.example.Arquivo.Professor> getProfessoresList() {
      return professores_;
    }
    /**
     * <code>repeated .com.example.Professor professores = 3;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.example.Arquivo.ProfessorOrBuilder> 
        getProfessoresOrBuilderList() {
      return professores_;
    }
    /**
     * <code>repeated .com.example.Professor professores = 3;</code>
     */
    @java.lang.Override
    public int getProfessoresCount() {
      return professores_.size();
    }
    /**
     * <code>repeated .com.example.Professor professores = 3;</code>
     */
    @java.lang.Override
    public com.example.Arquivo.Professor getProfessores(int index) {
      return professores_.get(index);
    }
    /**
     * <code>repeated .com.example.Professor professores = 3;</code>
     */
    @java.lang.Override
    public com.example.Arquivo.ProfessorOrBuilder getProfessoresOrBuilder(
        int index) {
      return professores_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNomeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, nome_);
      }
      if (anoInstituicao_ != 0) {
        output.writeInt32(2, anoInstituicao_);
      }
      for (int i = 0; i < professores_.size(); i++) {
        output.writeMessage(3, professores_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNomeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, nome_);
      }
      if (anoInstituicao_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, anoInstituicao_);
      }
      for (int i = 0; i < professores_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, professores_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.Arquivo.Universidade)) {
        return super.equals(obj);
      }
      com.example.Arquivo.Universidade other = (com.example.Arquivo.Universidade) obj;

      if (!getNome()
          .equals(other.getNome())) return false;
      if (getAnoInstituicao()
          != other.getAnoInstituicao()) return false;
      if (!getProfessoresList()
          .equals(other.getProfessoresList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NOME_FIELD_NUMBER;
      hash = (53 * hash) + getNome().hashCode();
      hash = (37 * hash) + ANOINSTITUICAO_FIELD_NUMBER;
      hash = (53 * hash) + getAnoInstituicao();
      if (getProfessoresCount() > 0) {
        hash = (37 * hash) + PROFESSORES_FIELD_NUMBER;
        hash = (53 * hash) + getProfessoresList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.Arquivo.Universidade parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.Arquivo.Universidade parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.Arquivo.Universidade parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.Arquivo.Universidade parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.Arquivo.Universidade parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.Arquivo.Universidade parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.Arquivo.Universidade parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.Arquivo.Universidade parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.Arquivo.Universidade parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.Arquivo.Universidade parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.Arquivo.Universidade parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.Arquivo.Universidade parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.Arquivo.Universidade prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.example.Universidade}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.example.Universidade)
        com.example.Arquivo.UniversidadeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.Arquivo.internal_static_com_example_Universidade_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.Arquivo.internal_static_com_example_Universidade_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.Arquivo.Universidade.class, com.example.Arquivo.Universidade.Builder.class);
      }

      // Construct using com.example.Arquivo.Universidade.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getProfessoresFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        nome_ = "";

        anoInstituicao_ = 0;

        if (professoresBuilder_ == null) {
          professores_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          professoresBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.Arquivo.internal_static_com_example_Universidade_descriptor;
      }

      @java.lang.Override
      public com.example.Arquivo.Universidade getDefaultInstanceForType() {
        return com.example.Arquivo.Universidade.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.Arquivo.Universidade build() {
        com.example.Arquivo.Universidade result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.Arquivo.Universidade buildPartial() {
        com.example.Arquivo.Universidade result = new com.example.Arquivo.Universidade(this);
        int from_bitField0_ = bitField0_;
        result.nome_ = nome_;
        result.anoInstituicao_ = anoInstituicao_;
        if (professoresBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            professores_ = java.util.Collections.unmodifiableList(professores_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.professores_ = professores_;
        } else {
          result.professores_ = professoresBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.Arquivo.Universidade) {
          return mergeFrom((com.example.Arquivo.Universidade)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.Arquivo.Universidade other) {
        if (other == com.example.Arquivo.Universidade.getDefaultInstance()) return this;
        if (!other.getNome().isEmpty()) {
          nome_ = other.nome_;
          onChanged();
        }
        if (other.getAnoInstituicao() != 0) {
          setAnoInstituicao(other.getAnoInstituicao());
        }
        if (professoresBuilder_ == null) {
          if (!other.professores_.isEmpty()) {
            if (professores_.isEmpty()) {
              professores_ = other.professores_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureProfessoresIsMutable();
              professores_.addAll(other.professores_);
            }
            onChanged();
          }
        } else {
          if (!other.professores_.isEmpty()) {
            if (professoresBuilder_.isEmpty()) {
              professoresBuilder_.dispose();
              professoresBuilder_ = null;
              professores_ = other.professores_;
              bitField0_ = (bitField0_ & ~0x00000001);
              professoresBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getProfessoresFieldBuilder() : null;
            } else {
              professoresBuilder_.addAllMessages(other.professores_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.Arquivo.Universidade parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.Arquivo.Universidade) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object nome_ = "";
      /**
       * <code>string nome = 1;</code>
       * @return The nome.
       */
      public java.lang.String getNome() {
        java.lang.Object ref = nome_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nome_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nome = 1;</code>
       * @return The bytes for nome.
       */
      public com.google.protobuf.ByteString
          getNomeBytes() {
        java.lang.Object ref = nome_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nome_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nome = 1;</code>
       * @param value The nome to set.
       * @return This builder for chaining.
       */
      public Builder setNome(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nome_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string nome = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNome() {
        
        nome_ = getDefaultInstance().getNome();
        onChanged();
        return this;
      }
      /**
       * <code>string nome = 1;</code>
       * @param value The bytes for nome to set.
       * @return This builder for chaining.
       */
      public Builder setNomeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nome_ = value;
        onChanged();
        return this;
      }

      private int anoInstituicao_ ;
      /**
       * <code>int32 anoInstituicao = 2;</code>
       * @return The anoInstituicao.
       */
      @java.lang.Override
      public int getAnoInstituicao() {
        return anoInstituicao_;
      }
      /**
       * <code>int32 anoInstituicao = 2;</code>
       * @param value The anoInstituicao to set.
       * @return This builder for chaining.
       */
      public Builder setAnoInstituicao(int value) {
        
        anoInstituicao_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 anoInstituicao = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAnoInstituicao() {
        
        anoInstituicao_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.example.Arquivo.Professor> professores_ =
        java.util.Collections.emptyList();
      private void ensureProfessoresIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          professores_ = new java.util.ArrayList<com.example.Arquivo.Professor>(professores_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.example.Arquivo.Professor, com.example.Arquivo.Professor.Builder, com.example.Arquivo.ProfessorOrBuilder> professoresBuilder_;

      /**
       * <code>repeated .com.example.Professor professores = 3;</code>
       */
      public java.util.List<com.example.Arquivo.Professor> getProfessoresList() {
        if (professoresBuilder_ == null) {
          return java.util.Collections.unmodifiableList(professores_);
        } else {
          return professoresBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.example.Professor professores = 3;</code>
       */
      public int getProfessoresCount() {
        if (professoresBuilder_ == null) {
          return professores_.size();
        } else {
          return professoresBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.example.Professor professores = 3;</code>
       */
      public com.example.Arquivo.Professor getProfessores(int index) {
        if (professoresBuilder_ == null) {
          return professores_.get(index);
        } else {
          return professoresBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.example.Professor professores = 3;</code>
       */
      public Builder setProfessores(
          int index, com.example.Arquivo.Professor value) {
        if (professoresBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProfessoresIsMutable();
          professores_.set(index, value);
          onChanged();
        } else {
          professoresBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.example.Professor professores = 3;</code>
       */
      public Builder setProfessores(
          int index, com.example.Arquivo.Professor.Builder builderForValue) {
        if (professoresBuilder_ == null) {
          ensureProfessoresIsMutable();
          professores_.set(index, builderForValue.build());
          onChanged();
        } else {
          professoresBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.example.Professor professores = 3;</code>
       */
      public Builder addProfessores(com.example.Arquivo.Professor value) {
        if (professoresBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProfessoresIsMutable();
          professores_.add(value);
          onChanged();
        } else {
          professoresBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.example.Professor professores = 3;</code>
       */
      public Builder addProfessores(
          int index, com.example.Arquivo.Professor value) {
        if (professoresBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProfessoresIsMutable();
          professores_.add(index, value);
          onChanged();
        } else {
          professoresBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.example.Professor professores = 3;</code>
       */
      public Builder addProfessores(
          com.example.Arquivo.Professor.Builder builderForValue) {
        if (professoresBuilder_ == null) {
          ensureProfessoresIsMutable();
          professores_.add(builderForValue.build());
          onChanged();
        } else {
          professoresBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.example.Professor professores = 3;</code>
       */
      public Builder addProfessores(
          int index, com.example.Arquivo.Professor.Builder builderForValue) {
        if (professoresBuilder_ == null) {
          ensureProfessoresIsMutable();
          professores_.add(index, builderForValue.build());
          onChanged();
        } else {
          professoresBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.example.Professor professores = 3;</code>
       */
      public Builder addAllProfessores(
          java.lang.Iterable<? extends com.example.Arquivo.Professor> values) {
        if (professoresBuilder_ == null) {
          ensureProfessoresIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, professores_);
          onChanged();
        } else {
          professoresBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.example.Professor professores = 3;</code>
       */
      public Builder clearProfessores() {
        if (professoresBuilder_ == null) {
          professores_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          professoresBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.example.Professor professores = 3;</code>
       */
      public Builder removeProfessores(int index) {
        if (professoresBuilder_ == null) {
          ensureProfessoresIsMutable();
          professores_.remove(index);
          onChanged();
        } else {
          professoresBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.example.Professor professores = 3;</code>
       */
      public com.example.Arquivo.Professor.Builder getProfessoresBuilder(
          int index) {
        return getProfessoresFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.example.Professor professores = 3;</code>
       */
      public com.example.Arquivo.ProfessorOrBuilder getProfessoresOrBuilder(
          int index) {
        if (professoresBuilder_ == null) {
          return professores_.get(index);  } else {
          return professoresBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.example.Professor professores = 3;</code>
       */
      public java.util.List<? extends com.example.Arquivo.ProfessorOrBuilder> 
           getProfessoresOrBuilderList() {
        if (professoresBuilder_ != null) {
          return professoresBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(professores_);
        }
      }
      /**
       * <code>repeated .com.example.Professor professores = 3;</code>
       */
      public com.example.Arquivo.Professor.Builder addProfessoresBuilder() {
        return getProfessoresFieldBuilder().addBuilder(
            com.example.Arquivo.Professor.getDefaultInstance());
      }
      /**
       * <code>repeated .com.example.Professor professores = 3;</code>
       */
      public com.example.Arquivo.Professor.Builder addProfessoresBuilder(
          int index) {
        return getProfessoresFieldBuilder().addBuilder(
            index, com.example.Arquivo.Professor.getDefaultInstance());
      }
      /**
       * <code>repeated .com.example.Professor professores = 3;</code>
       */
      public java.util.List<com.example.Arquivo.Professor.Builder> 
           getProfessoresBuilderList() {
        return getProfessoresFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.example.Arquivo.Professor, com.example.Arquivo.Professor.Builder, com.example.Arquivo.ProfessorOrBuilder> 
          getProfessoresFieldBuilder() {
        if (professoresBuilder_ == null) {
          professoresBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.example.Arquivo.Professor, com.example.Arquivo.Professor.Builder, com.example.Arquivo.ProfessorOrBuilder>(
                  professores_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          professores_ = null;
        }
        return professoresBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.example.Universidade)
    }

    // @@protoc_insertion_point(class_scope:com.example.Universidade)
    private static final com.example.Arquivo.Universidade DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.Arquivo.Universidade();
    }

    public static com.example.Arquivo.Universidade getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Universidade>
        PARSER = new com.google.protobuf.AbstractParser<Universidade>() {
      @java.lang.Override
      public Universidade parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Universidade(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Universidade> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Universidade> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.Arquivo.Universidade getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ProfessorOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.example.Professor)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string nome = 1;</code>
     * @return The nome.
     */
    java.lang.String getNome();
    /**
     * <code>string nome = 1;</code>
     * @return The bytes for nome.
     */
    com.google.protobuf.ByteString
        getNomeBytes();

    /**
     * <code>int32 idade = 2;</code>
     * @return The idade.
     */
    int getIdade();

    /**
     * <code>int32 anoDoutorado = 3;</code>
     * @return The anoDoutorado.
     */
    int getAnoDoutorado();

    /**
     * <code>repeated .com.example.Aluno alunos = 4;</code>
     */
    java.util.List<com.example.Arquivo.Aluno> 
        getAlunosList();
    /**
     * <code>repeated .com.example.Aluno alunos = 4;</code>
     */
    com.example.Arquivo.Aluno getAlunos(int index);
    /**
     * <code>repeated .com.example.Aluno alunos = 4;</code>
     */
    int getAlunosCount();
    /**
     * <code>repeated .com.example.Aluno alunos = 4;</code>
     */
    java.util.List<? extends com.example.Arquivo.AlunoOrBuilder> 
        getAlunosOrBuilderList();
    /**
     * <code>repeated .com.example.Aluno alunos = 4;</code>
     */
    com.example.Arquivo.AlunoOrBuilder getAlunosOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.example.Professor}
   */
  public static final class Professor extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.example.Professor)
      ProfessorOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Professor.newBuilder() to construct.
    private Professor(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Professor() {
      nome_ = "";
      alunos_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Professor();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Professor(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              nome_ = s;
              break;
            }
            case 16: {

              idade_ = input.readInt32();
              break;
            }
            case 24: {

              anoDoutorado_ = input.readInt32();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                alunos_ = new java.util.ArrayList<com.example.Arquivo.Aluno>();
                mutable_bitField0_ |= 0x00000001;
              }
              alunos_.add(
                  input.readMessage(com.example.Arquivo.Aluno.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          alunos_ = java.util.Collections.unmodifiableList(alunos_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.Arquivo.internal_static_com_example_Professor_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.Arquivo.internal_static_com_example_Professor_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.Arquivo.Professor.class, com.example.Arquivo.Professor.Builder.class);
    }

    public static final int NOME_FIELD_NUMBER = 1;
    private volatile java.lang.Object nome_;
    /**
     * <code>string nome = 1;</code>
     * @return The nome.
     */
    @java.lang.Override
    public java.lang.String getNome() {
      java.lang.Object ref = nome_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nome_ = s;
        return s;
      }
    }
    /**
     * <code>string nome = 1;</code>
     * @return The bytes for nome.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNomeBytes() {
      java.lang.Object ref = nome_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nome_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IDADE_FIELD_NUMBER = 2;
    private int idade_;
    /**
     * <code>int32 idade = 2;</code>
     * @return The idade.
     */
    @java.lang.Override
    public int getIdade() {
      return idade_;
    }

    public static final int ANODOUTORADO_FIELD_NUMBER = 3;
    private int anoDoutorado_;
    /**
     * <code>int32 anoDoutorado = 3;</code>
     * @return The anoDoutorado.
     */
    @java.lang.Override
    public int getAnoDoutorado() {
      return anoDoutorado_;
    }

    public static final int ALUNOS_FIELD_NUMBER = 4;
    private java.util.List<com.example.Arquivo.Aluno> alunos_;
    /**
     * <code>repeated .com.example.Aluno alunos = 4;</code>
     */
    @java.lang.Override
    public java.util.List<com.example.Arquivo.Aluno> getAlunosList() {
      return alunos_;
    }
    /**
     * <code>repeated .com.example.Aluno alunos = 4;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.example.Arquivo.AlunoOrBuilder> 
        getAlunosOrBuilderList() {
      return alunos_;
    }
    /**
     * <code>repeated .com.example.Aluno alunos = 4;</code>
     */
    @java.lang.Override
    public int getAlunosCount() {
      return alunos_.size();
    }
    /**
     * <code>repeated .com.example.Aluno alunos = 4;</code>
     */
    @java.lang.Override
    public com.example.Arquivo.Aluno getAlunos(int index) {
      return alunos_.get(index);
    }
    /**
     * <code>repeated .com.example.Aluno alunos = 4;</code>
     */
    @java.lang.Override
    public com.example.Arquivo.AlunoOrBuilder getAlunosOrBuilder(
        int index) {
      return alunos_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNomeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, nome_);
      }
      if (idade_ != 0) {
        output.writeInt32(2, idade_);
      }
      if (anoDoutorado_ != 0) {
        output.writeInt32(3, anoDoutorado_);
      }
      for (int i = 0; i < alunos_.size(); i++) {
        output.writeMessage(4, alunos_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNomeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, nome_);
      }
      if (idade_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, idade_);
      }
      if (anoDoutorado_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, anoDoutorado_);
      }
      for (int i = 0; i < alunos_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, alunos_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.Arquivo.Professor)) {
        return super.equals(obj);
      }
      com.example.Arquivo.Professor other = (com.example.Arquivo.Professor) obj;

      if (!getNome()
          .equals(other.getNome())) return false;
      if (getIdade()
          != other.getIdade()) return false;
      if (getAnoDoutorado()
          != other.getAnoDoutorado()) return false;
      if (!getAlunosList()
          .equals(other.getAlunosList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NOME_FIELD_NUMBER;
      hash = (53 * hash) + getNome().hashCode();
      hash = (37 * hash) + IDADE_FIELD_NUMBER;
      hash = (53 * hash) + getIdade();
      hash = (37 * hash) + ANODOUTORADO_FIELD_NUMBER;
      hash = (53 * hash) + getAnoDoutorado();
      if (getAlunosCount() > 0) {
        hash = (37 * hash) + ALUNOS_FIELD_NUMBER;
        hash = (53 * hash) + getAlunosList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.Arquivo.Professor parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.Arquivo.Professor parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.Arquivo.Professor parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.Arquivo.Professor parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.Arquivo.Professor parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.Arquivo.Professor parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.Arquivo.Professor parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.Arquivo.Professor parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.Arquivo.Professor parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.Arquivo.Professor parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.Arquivo.Professor parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.Arquivo.Professor parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.Arquivo.Professor prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.example.Professor}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.example.Professor)
        com.example.Arquivo.ProfessorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.Arquivo.internal_static_com_example_Professor_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.Arquivo.internal_static_com_example_Professor_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.Arquivo.Professor.class, com.example.Arquivo.Professor.Builder.class);
      }

      // Construct using com.example.Arquivo.Professor.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAlunosFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        nome_ = "";

        idade_ = 0;

        anoDoutorado_ = 0;

        if (alunosBuilder_ == null) {
          alunos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          alunosBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.Arquivo.internal_static_com_example_Professor_descriptor;
      }

      @java.lang.Override
      public com.example.Arquivo.Professor getDefaultInstanceForType() {
        return com.example.Arquivo.Professor.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.Arquivo.Professor build() {
        com.example.Arquivo.Professor result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.Arquivo.Professor buildPartial() {
        com.example.Arquivo.Professor result = new com.example.Arquivo.Professor(this);
        int from_bitField0_ = bitField0_;
        result.nome_ = nome_;
        result.idade_ = idade_;
        result.anoDoutorado_ = anoDoutorado_;
        if (alunosBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            alunos_ = java.util.Collections.unmodifiableList(alunos_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.alunos_ = alunos_;
        } else {
          result.alunos_ = alunosBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.Arquivo.Professor) {
          return mergeFrom((com.example.Arquivo.Professor)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.Arquivo.Professor other) {
        if (other == com.example.Arquivo.Professor.getDefaultInstance()) return this;
        if (!other.getNome().isEmpty()) {
          nome_ = other.nome_;
          onChanged();
        }
        if (other.getIdade() != 0) {
          setIdade(other.getIdade());
        }
        if (other.getAnoDoutorado() != 0) {
          setAnoDoutorado(other.getAnoDoutorado());
        }
        if (alunosBuilder_ == null) {
          if (!other.alunos_.isEmpty()) {
            if (alunos_.isEmpty()) {
              alunos_ = other.alunos_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureAlunosIsMutable();
              alunos_.addAll(other.alunos_);
            }
            onChanged();
          }
        } else {
          if (!other.alunos_.isEmpty()) {
            if (alunosBuilder_.isEmpty()) {
              alunosBuilder_.dispose();
              alunosBuilder_ = null;
              alunos_ = other.alunos_;
              bitField0_ = (bitField0_ & ~0x00000001);
              alunosBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAlunosFieldBuilder() : null;
            } else {
              alunosBuilder_.addAllMessages(other.alunos_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.Arquivo.Professor parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.Arquivo.Professor) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object nome_ = "";
      /**
       * <code>string nome = 1;</code>
       * @return The nome.
       */
      public java.lang.String getNome() {
        java.lang.Object ref = nome_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nome_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nome = 1;</code>
       * @return The bytes for nome.
       */
      public com.google.protobuf.ByteString
          getNomeBytes() {
        java.lang.Object ref = nome_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nome_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nome = 1;</code>
       * @param value The nome to set.
       * @return This builder for chaining.
       */
      public Builder setNome(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nome_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string nome = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNome() {
        
        nome_ = getDefaultInstance().getNome();
        onChanged();
        return this;
      }
      /**
       * <code>string nome = 1;</code>
       * @param value The bytes for nome to set.
       * @return This builder for chaining.
       */
      public Builder setNomeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nome_ = value;
        onChanged();
        return this;
      }

      private int idade_ ;
      /**
       * <code>int32 idade = 2;</code>
       * @return The idade.
       */
      @java.lang.Override
      public int getIdade() {
        return idade_;
      }
      /**
       * <code>int32 idade = 2;</code>
       * @param value The idade to set.
       * @return This builder for chaining.
       */
      public Builder setIdade(int value) {
        
        idade_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 idade = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearIdade() {
        
        idade_ = 0;
        onChanged();
        return this;
      }

      private int anoDoutorado_ ;
      /**
       * <code>int32 anoDoutorado = 3;</code>
       * @return The anoDoutorado.
       */
      @java.lang.Override
      public int getAnoDoutorado() {
        return anoDoutorado_;
      }
      /**
       * <code>int32 anoDoutorado = 3;</code>
       * @param value The anoDoutorado to set.
       * @return This builder for chaining.
       */
      public Builder setAnoDoutorado(int value) {
        
        anoDoutorado_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 anoDoutorado = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAnoDoutorado() {
        
        anoDoutorado_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.example.Arquivo.Aluno> alunos_ =
        java.util.Collections.emptyList();
      private void ensureAlunosIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          alunos_ = new java.util.ArrayList<com.example.Arquivo.Aluno>(alunos_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.example.Arquivo.Aluno, com.example.Arquivo.Aluno.Builder, com.example.Arquivo.AlunoOrBuilder> alunosBuilder_;

      /**
       * <code>repeated .com.example.Aluno alunos = 4;</code>
       */
      public java.util.List<com.example.Arquivo.Aluno> getAlunosList() {
        if (alunosBuilder_ == null) {
          return java.util.Collections.unmodifiableList(alunos_);
        } else {
          return alunosBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.example.Aluno alunos = 4;</code>
       */
      public int getAlunosCount() {
        if (alunosBuilder_ == null) {
          return alunos_.size();
        } else {
          return alunosBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.example.Aluno alunos = 4;</code>
       */
      public com.example.Arquivo.Aluno getAlunos(int index) {
        if (alunosBuilder_ == null) {
          return alunos_.get(index);
        } else {
          return alunosBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.example.Aluno alunos = 4;</code>
       */
      public Builder setAlunos(
          int index, com.example.Arquivo.Aluno value) {
        if (alunosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAlunosIsMutable();
          alunos_.set(index, value);
          onChanged();
        } else {
          alunosBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.example.Aluno alunos = 4;</code>
       */
      public Builder setAlunos(
          int index, com.example.Arquivo.Aluno.Builder builderForValue) {
        if (alunosBuilder_ == null) {
          ensureAlunosIsMutable();
          alunos_.set(index, builderForValue.build());
          onChanged();
        } else {
          alunosBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.example.Aluno alunos = 4;</code>
       */
      public Builder addAlunos(com.example.Arquivo.Aluno value) {
        if (alunosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAlunosIsMutable();
          alunos_.add(value);
          onChanged();
        } else {
          alunosBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.example.Aluno alunos = 4;</code>
       */
      public Builder addAlunos(
          int index, com.example.Arquivo.Aluno value) {
        if (alunosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAlunosIsMutable();
          alunos_.add(index, value);
          onChanged();
        } else {
          alunosBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.example.Aluno alunos = 4;</code>
       */
      public Builder addAlunos(
          com.example.Arquivo.Aluno.Builder builderForValue) {
        if (alunosBuilder_ == null) {
          ensureAlunosIsMutable();
          alunos_.add(builderForValue.build());
          onChanged();
        } else {
          alunosBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.example.Aluno alunos = 4;</code>
       */
      public Builder addAlunos(
          int index, com.example.Arquivo.Aluno.Builder builderForValue) {
        if (alunosBuilder_ == null) {
          ensureAlunosIsMutable();
          alunos_.add(index, builderForValue.build());
          onChanged();
        } else {
          alunosBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.example.Aluno alunos = 4;</code>
       */
      public Builder addAllAlunos(
          java.lang.Iterable<? extends com.example.Arquivo.Aluno> values) {
        if (alunosBuilder_ == null) {
          ensureAlunosIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, alunos_);
          onChanged();
        } else {
          alunosBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.example.Aluno alunos = 4;</code>
       */
      public Builder clearAlunos() {
        if (alunosBuilder_ == null) {
          alunos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          alunosBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.example.Aluno alunos = 4;</code>
       */
      public Builder removeAlunos(int index) {
        if (alunosBuilder_ == null) {
          ensureAlunosIsMutable();
          alunos_.remove(index);
          onChanged();
        } else {
          alunosBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.example.Aluno alunos = 4;</code>
       */
      public com.example.Arquivo.Aluno.Builder getAlunosBuilder(
          int index) {
        return getAlunosFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.example.Aluno alunos = 4;</code>
       */
      public com.example.Arquivo.AlunoOrBuilder getAlunosOrBuilder(
          int index) {
        if (alunosBuilder_ == null) {
          return alunos_.get(index);  } else {
          return alunosBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.example.Aluno alunos = 4;</code>
       */
      public java.util.List<? extends com.example.Arquivo.AlunoOrBuilder> 
           getAlunosOrBuilderList() {
        if (alunosBuilder_ != null) {
          return alunosBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(alunos_);
        }
      }
      /**
       * <code>repeated .com.example.Aluno alunos = 4;</code>
       */
      public com.example.Arquivo.Aluno.Builder addAlunosBuilder() {
        return getAlunosFieldBuilder().addBuilder(
            com.example.Arquivo.Aluno.getDefaultInstance());
      }
      /**
       * <code>repeated .com.example.Aluno alunos = 4;</code>
       */
      public com.example.Arquivo.Aluno.Builder addAlunosBuilder(
          int index) {
        return getAlunosFieldBuilder().addBuilder(
            index, com.example.Arquivo.Aluno.getDefaultInstance());
      }
      /**
       * <code>repeated .com.example.Aluno alunos = 4;</code>
       */
      public java.util.List<com.example.Arquivo.Aluno.Builder> 
           getAlunosBuilderList() {
        return getAlunosFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.example.Arquivo.Aluno, com.example.Arquivo.Aluno.Builder, com.example.Arquivo.AlunoOrBuilder> 
          getAlunosFieldBuilder() {
        if (alunosBuilder_ == null) {
          alunosBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.example.Arquivo.Aluno, com.example.Arquivo.Aluno.Builder, com.example.Arquivo.AlunoOrBuilder>(
                  alunos_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          alunos_ = null;
        }
        return alunosBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.example.Professor)
    }

    // @@protoc_insertion_point(class_scope:com.example.Professor)
    private static final com.example.Arquivo.Professor DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.Arquivo.Professor();
    }

    public static com.example.Arquivo.Professor getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Professor>
        PARSER = new com.google.protobuf.AbstractParser<Professor>() {
      @java.lang.Override
      public Professor parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Professor(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Professor> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Professor> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.Arquivo.Professor getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AlunoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.example.Aluno)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string nome = 1;</code>
     * @return The nome.
     */
    java.lang.String getNome();
    /**
     * <code>string nome = 1;</code>
     * @return The bytes for nome.
     */
    com.google.protobuf.ByteString
        getNomeBytes();

    /**
     * <code>int32 idade = 2;</code>
     * @return The idade.
     */
    int getIdade();

    /**
     * <code>int32 avaliacao = 3;</code>
     * @return The avaliacao.
     */
    int getAvaliacao();
  }
  /**
   * Protobuf type {@code com.example.Aluno}
   */
  public static final class Aluno extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.example.Aluno)
      AlunoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Aluno.newBuilder() to construct.
    private Aluno(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Aluno() {
      nome_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Aluno();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Aluno(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              nome_ = s;
              break;
            }
            case 16: {

              idade_ = input.readInt32();
              break;
            }
            case 24: {

              avaliacao_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.Arquivo.internal_static_com_example_Aluno_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.Arquivo.internal_static_com_example_Aluno_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.Arquivo.Aluno.class, com.example.Arquivo.Aluno.Builder.class);
    }

    public static final int NOME_FIELD_NUMBER = 1;
    private volatile java.lang.Object nome_;
    /**
     * <code>string nome = 1;</code>
     * @return The nome.
     */
    @java.lang.Override
    public java.lang.String getNome() {
      java.lang.Object ref = nome_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nome_ = s;
        return s;
      }
    }
    /**
     * <code>string nome = 1;</code>
     * @return The bytes for nome.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNomeBytes() {
      java.lang.Object ref = nome_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nome_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IDADE_FIELD_NUMBER = 2;
    private int idade_;
    /**
     * <code>int32 idade = 2;</code>
     * @return The idade.
     */
    @java.lang.Override
    public int getIdade() {
      return idade_;
    }

    public static final int AVALIACAO_FIELD_NUMBER = 3;
    private int avaliacao_;
    /**
     * <code>int32 avaliacao = 3;</code>
     * @return The avaliacao.
     */
    @java.lang.Override
    public int getAvaliacao() {
      return avaliacao_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNomeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, nome_);
      }
      if (idade_ != 0) {
        output.writeInt32(2, idade_);
      }
      if (avaliacao_ != 0) {
        output.writeInt32(3, avaliacao_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNomeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, nome_);
      }
      if (idade_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, idade_);
      }
      if (avaliacao_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, avaliacao_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.Arquivo.Aluno)) {
        return super.equals(obj);
      }
      com.example.Arquivo.Aluno other = (com.example.Arquivo.Aluno) obj;

      if (!getNome()
          .equals(other.getNome())) return false;
      if (getIdade()
          != other.getIdade()) return false;
      if (getAvaliacao()
          != other.getAvaliacao()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NOME_FIELD_NUMBER;
      hash = (53 * hash) + getNome().hashCode();
      hash = (37 * hash) + IDADE_FIELD_NUMBER;
      hash = (53 * hash) + getIdade();
      hash = (37 * hash) + AVALIACAO_FIELD_NUMBER;
      hash = (53 * hash) + getAvaliacao();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.Arquivo.Aluno parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.Arquivo.Aluno parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.Arquivo.Aluno parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.Arquivo.Aluno parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.Arquivo.Aluno parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.Arquivo.Aluno parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.Arquivo.Aluno parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.Arquivo.Aluno parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.Arquivo.Aluno parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.Arquivo.Aluno parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.Arquivo.Aluno parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.Arquivo.Aluno parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.Arquivo.Aluno prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.example.Aluno}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.example.Aluno)
        com.example.Arquivo.AlunoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.Arquivo.internal_static_com_example_Aluno_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.Arquivo.internal_static_com_example_Aluno_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.Arquivo.Aluno.class, com.example.Arquivo.Aluno.Builder.class);
      }

      // Construct using com.example.Arquivo.Aluno.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        nome_ = "";

        idade_ = 0;

        avaliacao_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.Arquivo.internal_static_com_example_Aluno_descriptor;
      }

      @java.lang.Override
      public com.example.Arquivo.Aluno getDefaultInstanceForType() {
        return com.example.Arquivo.Aluno.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.Arquivo.Aluno build() {
        com.example.Arquivo.Aluno result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.Arquivo.Aluno buildPartial() {
        com.example.Arquivo.Aluno result = new com.example.Arquivo.Aluno(this);
        result.nome_ = nome_;
        result.idade_ = idade_;
        result.avaliacao_ = avaliacao_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.Arquivo.Aluno) {
          return mergeFrom((com.example.Arquivo.Aluno)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.Arquivo.Aluno other) {
        if (other == com.example.Arquivo.Aluno.getDefaultInstance()) return this;
        if (!other.getNome().isEmpty()) {
          nome_ = other.nome_;
          onChanged();
        }
        if (other.getIdade() != 0) {
          setIdade(other.getIdade());
        }
        if (other.getAvaliacao() != 0) {
          setAvaliacao(other.getAvaliacao());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.Arquivo.Aluno parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.Arquivo.Aluno) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object nome_ = "";
      /**
       * <code>string nome = 1;</code>
       * @return The nome.
       */
      public java.lang.String getNome() {
        java.lang.Object ref = nome_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nome_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nome = 1;</code>
       * @return The bytes for nome.
       */
      public com.google.protobuf.ByteString
          getNomeBytes() {
        java.lang.Object ref = nome_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nome_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nome = 1;</code>
       * @param value The nome to set.
       * @return This builder for chaining.
       */
      public Builder setNome(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nome_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string nome = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNome() {
        
        nome_ = getDefaultInstance().getNome();
        onChanged();
        return this;
      }
      /**
       * <code>string nome = 1;</code>
       * @param value The bytes for nome to set.
       * @return This builder for chaining.
       */
      public Builder setNomeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nome_ = value;
        onChanged();
        return this;
      }

      private int idade_ ;
      /**
       * <code>int32 idade = 2;</code>
       * @return The idade.
       */
      @java.lang.Override
      public int getIdade() {
        return idade_;
      }
      /**
       * <code>int32 idade = 2;</code>
       * @param value The idade to set.
       * @return This builder for chaining.
       */
      public Builder setIdade(int value) {
        
        idade_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 idade = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearIdade() {
        
        idade_ = 0;
        onChanged();
        return this;
      }

      private int avaliacao_ ;
      /**
       * <code>int32 avaliacao = 3;</code>
       * @return The avaliacao.
       */
      @java.lang.Override
      public int getAvaliacao() {
        return avaliacao_;
      }
      /**
       * <code>int32 avaliacao = 3;</code>
       * @param value The avaliacao to set.
       * @return This builder for chaining.
       */
      public Builder setAvaliacao(int value) {
        
        avaliacao_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 avaliacao = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAvaliacao() {
        
        avaliacao_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.example.Aluno)
    }

    // @@protoc_insertion_point(class_scope:com.example.Aluno)
    private static final com.example.Arquivo.Aluno DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.Arquivo.Aluno();
    }

    public static com.example.Arquivo.Aluno getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Aluno>
        PARSER = new com.google.protobuf.AbstractParser<Aluno>() {
      @java.lang.Override
      public Aluno parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Aluno(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Aluno> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Aluno> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.Arquivo.Aluno getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_Universidade_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_Universidade_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_Professor_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_Professor_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_Aluno_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_Aluno_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rarquivo.proto\022\013com.example\"a\n\014Universi" +
      "dade\022\014\n\004nome\030\001 \001(\t\022\026\n\016anoInstituicao\030\002 \001" +
      "(\005\022+\n\013professores\030\003 \003(\0132\026.com.example.Pr" +
      "ofessor\"b\n\tProfessor\022\014\n\004nome\030\001 \001(\t\022\r\n\005id" +
      "ade\030\002 \001(\005\022\024\n\014anoDoutorado\030\003 \001(\005\022\"\n\006aluno" +
      "s\030\004 \003(\0132\022.com.example.Aluno\"7\n\005Aluno\022\014\n\004" +
      "nome\030\001 \001(\t\022\r\n\005idade\030\002 \001(\005\022\021\n\tavaliacao\030\003" +
      " \001(\005b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_example_Universidade_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_Universidade_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_Universidade_descriptor,
        new java.lang.String[] { "Nome", "AnoInstituicao", "Professores", });
    internal_static_com_example_Professor_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_example_Professor_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_Professor_descriptor,
        new java.lang.String[] { "Nome", "Idade", "AnoDoutorado", "Alunos", });
    internal_static_com_example_Aluno_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_example_Aluno_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_Aluno_descriptor,
        new java.lang.String[] { "Nome", "Idade", "Avaliacao", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
